### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
I took your suggestion of using a compare application, which was a good idea as it allowed me to easily see the changes. I hope I did it right!

Btw, thanks for notifying me about the updated strings. Not every dev does that, so I really appreciate that you did! 🙂

### CODE REVIEW

**Comment by erosman** [comment]
Thank you.

Are these the same?

"extensionDescription": { "message": "Format Text, Replace, Insert HTML, BBCode, Markdown & Custom Texts" },

"extensionDescription": { "message": "Voorzie tekst van opmaak en voeg html, bbcode en aangepaste teksten in" },

**Comment by Vistaus** [comment]
Yes, those are the same.

**Comment by erosman** [comment]
I dont see Markdown or Replace?

Google translate:
Voorzie tekst van opmaak en voeg html, bbcode en aangepaste teksten in
-> Format text and insert html, bbcode and custom texts 

Google translate:
Format Text, Replace, Insert HTML, BBCode, Markdown & Custom Texts
-> Tekst opmaken, vervangen, HTML invoegen, BBCode, Markdown en aangepaste teksten

**Comment by Vistaus** [comment]
Oops, forgot to add those to the sentence. Thanks for noticing - I fixed it just now!

**Pull request merged**
